### ISSUE TITLE
Grails 3.2.x Command new terms

### ISSUE THREAD

**Issue by KoloritnijClap** [grails-plugins/grails-database-migration#101]
Regarding new rules for Commands: http://docs.grails.org/3.2.3/guide/single.html#creatingCustomCommands
Please, update command in plugin, they should implement: [GrailsApplicationCommand](http://docs.grails.org/latest/api/grails/dev/commands/GrailsApplicationCommand.html)

**Comment by jameskleeh** [comment]
Why? What problem are you facing?

**Comment by KoloritnijClap** [comment]
@jameskleeh I use grails 3.2.3(java1.8.0_102) and I can't run any dbm-* commands, only dbm-changelog-to-groovy and dbm-create-changelog. It wrote that cannot find command.

**Comment by jameskleeh** [comment]
Create an example project that demonstrates the issue and link to it here

**Comment by jameskleeh** [comment]
Also document steps to reproduce

**Comment by KoloritnijClap** [comment]
@jameskleeh https://github.com/KoloritnijClap/command-issue here it is a main project named project-a and a core plugin that contain all domains. In project-a I can't run any dbm-* commands. The main thing that changelog.groovy should be in core plugin, that I can access it from another project(for example project-b)

**Comment by jameskleeh** [comment]
Please provide steps to reproduce the issue

**Comment by KoloritnijClap** [comment]
@jameskleeh go to project-a dir -> run grails CLI -> it impossible to run any dbm-* commands, also if press TAB you will not see they in command list.

**Comment by KoloritnijClap** [comment]
Had issue on macOs Sierra and Linux Ubuntu 16.04

**Comment by jameskleeh** [comment]
The reason looks to be a missing dependency.

`java.lang.ClassNotFoundException: org.hibernate.tool.schema.TargetType`

**Comment by jameskleeh** [comment]
You are missing this in your build.gradle:

```
    compile "org.hibernate:hibernate-core:5.1.2.Final"
    compile "org.hibernate:hibernate-ehcache:5.1.2.Final"
```

**Comment by KoloritnijClap** [comment]
@jameskleeh I have
`compile 'org.grails.plugins:hibernate5:6.0.4'
    compile "org.hibernate:hibernate-ehcache"`
Should I change it to 5.1.2?
