### ISSUE TITLE
Default dataSource is excluded from dataSources if I have them

### ISSUE THREAD

**Issue by Kipriz** [grails-plugins/grails-database-migration#102]
I have the following database configuration: 1 master database (default dataSource in Grails) and a few multitenant databases (under dataSources in Grails).
I see the following in `DatabaseMigrationCommand.groovy`:
```
Map<String, String> getDataSourceConfig(ConfigMap config = this.config) {
        def dataSourceName = dataSource ?: 'dataSource'
        def dataSources = config.getProperty('dataSources', Map) ?: [:]
        if (!dataSources) {
            def defaultDataSource = config.getProperty('dataSource', Map)
            if (defaultDataSource) {
                dataSources['dataSource'] = defaultDataSource
            }
        }
        return (Map<String, String>) dataSources.get(dataSourceName)
    }
```
So, default dataSource is excluded if I have declared dataSources. It looks wrong to me.
Is it done by intent? What is the reason to exclude default data source? Is it safe to always include default data source?

PS I can provide a patch for this if needed.

**Comment by jameskleeh** [comment]
If you are declaring multiple data sources, they must all be under the `dataSources` key, with the default data source being named `dataSource`. Provide an example application demonstrating behavior you think is a bug and I can take a look.

**Comment by jameskleeh** [comment]
Closing because no feedback provided
