### ISSUE TITLE
hibernate-envers - UnsupportedOperationException

### ISSUE THREAD

**Issue by zyro23** [grails-plugins/grails-database-migration#104]
dbm-3.0.0, grails-3.2.3, gorm-6.0.4, hibernate-5.0.11.

when using hibernate envers, all liquibase commands that involve two databases (e.g. dbm-gorm-diff - 1 gorm db, 1 real db) cause an `UnsupportedOperationException` here:
https://github.com/hibernate/hibernate-orm/blob/5.0.11/hibernate-envers/src/main/java/org/hibernate/envers/boot/internal/EnversServiceImpl.java#L107

ugly workaround for now was to write a custom `ÈnversService` / `ServiceContributor` / `ServiceInitiator` that overrides the default hibernate `EnversServiceImpl`.

do we have any sane option to prevent that from happening or should we raise an upstream issue for hibernate-envers explaining the dbm diff use-case and request to remove that condition?

**Comment by jameskleeh** [comment]
Can you include the stacktrace? I doubt hibernate would consider changing that for our use case.

**Comment by jameskleeh** [comment]
@zyro23 I don't think there is anything I can do on this end. I see the issue you linked is closed. Does that satisfy your requirement?

**Comment by zyro23** [comment]
linked issue has kind of a follow up as it fixed being able to register a custom service in envers but now the configuration of a custom mappingContextConfiguration is not working. ref. https://github.com/grails/gorm-hibernate5/issues/17

anyway, thats the right place where this should be fixed. closing this one here. thanks!

**Comment by RobertStroud** [comment]
@zyro23 can you provide more information about your "ugly workaround"? Is this something that needs to be fixed in the "database-migration" plugin, or does it need to be fixed in the interface between Grails and Envers, for example, in an Envers plugin?

I am experiencing the same problem using Grails 3.2.12 with GORM 6.1.6 and a version of the "grails-envers" plugin that has been ported to Grails 3.

Thanks.

**Comment by zyro23** [comment]
ref. https://hibernate.atlassian.net/browse/HHH-12089

**Comment by cgoIT** [comment]
I know that this issue was closed a long time ago, but i'm lost in getting dbm-gorm-diff running. Could you please give me some advice how to do it?

Thanks.

**Comment by xavs** [comment]
Same here, the plugin is broken for grails 4.

**Comment by davebrown1975** [comment]
Any update at all ?

**Comment by verglor** [comment]
There is open issue https://github.com/grails/gorm-hibernate5/issues/984 for this.

**Comment by jamesfredley** [comment]
This is at least partially addressed in https://github.com/grails/grails-database-migration/pull/366 based on

https://github.com/grails/gorm-hibernate5/blob/8.1.x/grails-plugin/src/main/groovy/grails/plugin/hibernate/commands/SchemaExportCommand.groovy#L70
