### ISSUE TITLE
Cannot run plugin scripts on empty DB

### ISSUE THREAD

**Issue by azhuchkov** [grails-plugins/grails-database-migration#105]
Neither `dbm-update`, nor `dbm-status` do not work, because they bootstrap application which requires tables and fails due to that. Additionally it is time-consuming.

Is it possible to run migration scripts without bootstrapping application?

Grails: 2.3.11
Migration Plugin: 1.4.1

**Comment by jameskleeh** [comment]
I'm 95% sure that behavior was not happening with the Grails 2 version of the plugin. It was happening with the 2.0 RC releases and was fixed in 2.0/3.0.

Either way, the 1.x line of the plugin isn't being maintained. I suggest you upgrade to Grails 3 and version 2.0/3.0 of the plugin which has newer liquibase support.

**Comment by azhuchkov** [comment]
I'm 99% sure this is not related to `grails.bootstrap.skip` option introduced in Grails 3.x.

Consider this scenario:
1. `grails dbm-status` command is fired which invokes script `DbmStatus.groovy`
2. script `_DatabaseMigrationCommon.groovy` is evaluated. It has several dependencies and `bootstrapOnce` among them.
3. Grails application is launched and takes so much time for application context configuration (is it really necessary for `dbm-status`? Wouldn't `createConfig` dependency fit better?).
4. During app initialisation **Quartz plugin** *init script* has been launched.
5. Under `doWithApplicationContext` the **Quartz plugin** invokes `scheduler.addJob(jobDetail, true)` which fires `SQL INSERT` statement since it's configured to use **JDBC** job store.
6. **Fail**… (we do not have tables in database so far - we just want to get DB status).

Does this scenario work in Grails 3.x?

Anyway we cannot migrate to version 3.x so far, so back port would be appreciated.

**Comment by jameskleeh** [comment]
So when you said "bootstrapping application", I believed you meant the execution of Bootstrap.groovy. Now I am understanding that is not what you meant, and instead are talking about Quartz firing some SQL that is not appropriate.

That scenario would occur with any version of Grails and any version of the dbm plugin. The migration plugin certainly can't control what other plugins do or do not do. My suggestion is to disable quartz while working with the migrations plugin or create the required tables ahead of time.

**Comment by azhuchkov** [comment]
Yep, when application context is being initialised anything can happen. The question is: why application context initialization is required for such dbm operations like *status*, *validate*, *update* and others which IMO requires DB connection parameters only?

**Comment by jameskleeh** [comment]
The datasource is registered and retrieved as a bean. That requires the context.

**Comment by azhuchkov** [comment]
Ok. I thought it can be done like this: http://mrhaki.blogspot.ru/2011/03/grails-goodness-access-configuration-in.html

**Comment by jameskleeh** [comment]
No. It would not be wise or practical to duplicate all of the logic on how to create a dataSource for all database implementations in the migrations plugin.

**Comment by azhuchkov** [comment]
Sure. Figuring out what has been failed, why and what should be disabled and when enabled again is very practical. :)
