### ISSUE TITLE
Command not found dbm-generate-gorm-changelog

### ISSUE THREAD

**Issue by MichaelMorett** [grails-plugins/grails-database-migration#107]
Per the documentation here: [http://grails-plugins.github.io/grails-database-migration/3.0.x/index.html#gettingStarted](url)

I followed the instructions to execute this command:
**grails dbm-generate-gorm-changelog changelog.groovy**

It immediately fails. 
**| Error Command not found dbm-generate-gorm-changelog**
Did you mean: dbm-create-changelog or dbm-changelog-to-groovy or generate-all?

Using:
Grails 3.1.12
compile "org.grails.plugins:database-migration:3.0.0"  
compile 'org.liquibase:liquibase-core:3.5.3'

**Comment by jameskleeh** [comment]
Do you have it listed as a classpath dependency in the buildscript section?

**Comment by MichaelMorett** [comment]
Hi James.  Yes.

    dependencies {
        classpath "org.grails:grails-gradle-plugin:$grailsVersion"
        classpath "com.bertramlabs.plugins:asset-pipeline-gradle:2.8.2"
        classpath "org.grails.plugins:hibernate5:5.0.11"
        classpath 'org.grails.plugins:database-migration:3.0.0'
    }

**Comment by jameskleeh** [comment]
Please provide an example project that demonstrates the problem

**Comment by MichaelMorett** [comment]
Appreciate the attempt to help but I can't switch gears.  I've got work on my plate.

**Comment by jameskleeh** [comment]
OK. If you are ever inclined to create an example project, feel free to create a new issue.
