### ISSUE TITLE
 Command not found dbm-generate-gorm-changelog

### ISSUE THREAD

**Issue by MichaelMorett** [grails-plugins/grails-database-migration#108]
This is the same as Issue #107 which was closed earlier due to not having a sample project to show the issue. 

A sample project can be found here:
https://github.com/MichaelMorett/dbmigration

After more testing and experimentation, issue seems to be related to Hibernate5.

==============

Per the documentation here: http://grails-plugins.github.io/grails-database-migration/3.0.x/index.html#gettingStarted

I followed the instructions to execute this command:
grails dbm-generate-gorm-changelog changelog.groovy

It immediately fails.
| Error Command not found dbm-generate-gorm-changelog
Did you mean: dbm-create-changelog or dbm-changelog-to-groovy or generate-all?

Using:
Grails 3.1.12
compile "org.grails.plugins:database-migration:3.0.0"
compile 'org.liquibase:liquibase-core:3.5.3'

**Comment by MichaelMorett** [comment]
I wanted to provide additional info...

Taking the same exact source code found here...
https://github.com/MichaelMorett/dbmigration

...but with a virgin app **built with Grails 3.2.3** (instead of 3.1.12),  the problems went away. 

More specifically,  these are the substantive points of change:

Grails 3.2.3 defaults
buildscript dependency
    **classpath org.grails.plugins:hibernate5:6.0.4** 

dependencies
    **compile "org.grails.plugins:hibernate5"**
    **compile "org.hibernate:hibernate-core:5.1.2.Final"**
    **compile "org.hibernate:hibernate-ehcache:5.1.2.Final"**

====================

I'm going to propose we upgrade to 3.2.3 for our apps.  This may be a bug not worth fixing.

**Comment by jameskleeh** [comment]
So what is actually failing is the SchemaExportCommand. My guess is the version of hibernate-core, 5.0.11 is not compatible with the version of the hibernate plugin you have specified.

**Comment by jameskleeh** [comment]
If you want to stay on Gorm 5, you should be using:

Hibernate version: 5.1.0
Gorm version: 5.0.12

```
    compile "org.grails.plugins:hibernate5:5.0.12"               //Hibernate 5
    compile "org.hibernate:hibernate-core:5.1.0.Final"          //Hibernate 5
    compile "org.hibernate:hibernate-ehcache:5.1.0.Final"       //Hibernate 5
```

Then the command works.

**Comment by jameskleeh** [comment]
If you want to stick with hibernate 5.0.x you need to be using 5.0.4 of the plugin:

```
    compile "org.grails.plugins:hibernate5:5.0.4"               //Hibernate 5
    compile "org.hibernate:hibernate-core:5.0.7.Final"          //Hibernate 5
    compile "org.hibernate:hibernate-ehcache:5.0.7.Final"       //Hibernate 5
```

**Comment by MichaelMorett** [comment]
Thanks for the info James.  

We agreed to move to Grails 3.2.3.   So far, various tests are failing and the app won't start.  Doing a Grails 3 upgrade has been utter hell.  Horrible.  Just horrible.

**Comment by jameskleeh** [comment]
@MichaelMorett Can you send me an email with your major pain points? kleehj@ociweb.com

**Comment by MichaelMorett** [comment]
Pain points sent via email, James.   Cheers...
