### ISSUE TITLE
dbmGenerateChangeLog frozen

### ISSUE THREAD

**Issue by liftyourgame** [grails-plugins/grails-database-migration#112]
I have a grails 3.2.3 project with Hibernate5

I've set up version 3.0.0 of the migration plugin.

When I run:

grails dbm-generate-changelog changelog.groovy

compileJava UP-TO-DATE
:compileGroovy UP-TO-DATE
:buildProperties UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:findMainClass
:dbmGenerateChangelog
objc[70710]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin/java (0x10e0af4c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x10e1774e0). One of the two will be used. Which one is undefined.
> Building 85% > :dbmGenerateChangelog

It just freezes at 85%.

**Comment by jameskleeh** [comment]
Does it happen every time?

**Comment by liftyourgame** [comment]
Yes. Everytime. I'm trying to generate the initial change log.

**Comment by liftyourgame** [comment]
Not sure what changed but seems to be working now
