### ISSUE TITLE
No such property databaseChangeLog

### ISSUE THREAD

**Issue by liftyourgame** [grails-plugins/grails-database-migration#113]
When running:

grails dbm-changelog-sync

I get the following error.

INFO 20/12/16 12:06 PM: liquibase: Can not use class org.grails.plugins.databasemigration.liquibase.GormDatabase as a Liquibase service because it does not have a no-argument constructor
Command execution error: groovy.lang.MissingPropertyException: No such property: databaseChangeLog for class: Script1
:dbmChangelogSync FAILED

I have included in dependencies:

    compile 'org.liquibase:liquibase-core:3.5.3'

as per the documentation.

**Comment by liftyourgame** [comment]
Seems to work ok despite the error.

**Comment by jameskleeh** [comment]
Attach an example project and I'll take a look

**Comment by halfhp** [comment]
I'm seeing this during startup as well.  No noticeable side effects yet tho.

**Comment by schmickie** [comment]
I am also seeing this during startup in a grails 3.2.4 project.

```    compile "org.grails.plugins:database-migration:3.0.0"
    compile 'org.liquibase:liquibase-core:3.5.3'
```

**Comment by jameskleeh** [comment]
Closing this as no example project attached. If you are still facing this problem, open a new issue with an example project.
