### ISSUE TITLE
springsecurityservice dependency injection fails during dbm updates

### ISSUE THREAD

**Issue by edwardotis** [grails-plugins/grails-database-migration#114]
So, the thread  in issue https://github.com/grails-plugins/grails-database-migration/issues/42 appears to have gotten off topic from the initial question, and focused on skipping Bootstrap.groovy. I'm opening a new issue to focus on the original plugin load order issue.

I'm having a similar problem as issue https://github.com/grails-plugins/grails-database-migration/issues/42 calling User.encodePassword() from within a dbm changeSet. The springsecurityservice bean used for encoding is not injected into User in grails 3.1, but it was injected properly in grails 2.5.5 during dbm-update. My existing migration was broken by this change in functionality when I moved from grails 2.5 to 3.1

Can the db plugin be loaded after spring-security-core?

Grails 3.1.14
database-migration:2.0.0
spring-security-core:3.1.1

**Comment by jameskleeh** [comment]
I don't see how that would make a difference since the User class isn't created until after the application is started (after all plugins are loaded)

**Comment by edwardotis** [comment]
@jameskleeh Thanks, any other ideas why this dependency injection is failing?

**Comment by jameskleeh** [comment]
@edwardotis Not really. If you attach an example project I can take a look

**Comment by jameskleeh** [comment]
Closing due to no example attached
