### ISSUE TITLE
PSQL schema_name ignored

### ISSUE THREAD

**Issue by immutability** [grails-plugins/grails-database-migration#120]
We've recently migrated our Grails 2.5.x app to Grails 3.1.x and are facing an issue with our production environment, which is using PostgreSQL with a non-standard schema (i.e. not 'public'). 

In Grails itself, this can be configured in the dataSource block of application.groovy as:
```
dataSource {
   driverClassName = "org.postgresql.Driver"
   dialect = "org.hibernate.dialect.PostgreSQLDialect"
   username = ""
   password = ""
   url = ""
   hibernate.default_schema = "eos"
}
```

This worked fine in Grails 2 but fails in Grails 3, with this exception:
> liquibase.exception.DatabaseException: ERROR: no schema has been selected to create in
>  Position: 14 [Failed SQL: CREATE TABLE databasechangeloglock (ID INT NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP WITHOUT TIME ZONE, LOCKEDBY VARCHAR(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID))]

Grails itself works correctly if liquibase is by-passed (i.e. if updateOnStart is set to false). Is there some extra configuration needed for this to work? We're on Hibernate 4 so using version 2.0.0 of the plugin and reproduced the issue with liquibase 3.4.2 and 3.5.3. Not sure if this is a bug or if we're doing something wrong. Thanks for any hints!

**Comment by bobbywarner** [comment]
You need to also set: `grails.plugin.databasemigration.updateOnStartDefaultSchema`

**Comment by immutability** [comment]
@bobbywarner Thank you, that was it!
