### ISSUE TITLE
Please enable support for Custom Environments

### ISSUE THREAD

**Issue by rrsIPOV** [grails-plugins/grails-database-migration#126]
### Task List

- [x] Steps to reproduce provided
- [-] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a Grails app using latest stable release.
2. Add grails-database-migration v3 to gradle.build
3. Add some domain classes
4. For demonstration - change development environment to use a H2 file instead of memory db.
5. Setup development environment to auto apply changes via grails-database-migration, turning off hibernate change management.
6. Execute 'grails run-app'
7. Navigate to http://localhost:8080/dbconsole and verify that the file DB exists and has the expected changes.
8. Stop the app.
9. Copy the current db (devDB) to a different name (rdataDB).
10. Add a custom environment to application.yml called datatool which uses the rdataDB file.  This represents a remote DB which in practice is connected to via SSH tunnel.
11. Make changes to domain class(es) and update your changelog.groovy.
12. Execute 'grails run-app' and go to the dbconsole to see that they are applied.  Stop the app.
13. Execute 'grails -Dgrails.env=datatool dbm-update'  - if you check the logs you'll see that the environment is listed as 'development'.  If you start the app again and use the dbconsole, or use some other h2 tool, you will see that the changes have not been applied to the custom environment.

### Expected Behaviour

The plugin should support custom environments.

### Actual Behaviour

The plugin ignores custom environments and defaults to the standard development env.

### Environment Information

- **Operating System**: Windows 7 x64
- **Grails Version:** 3.2.7
- **Plugin Version:** 3.0.0
- **Database:**  H2 (and MySQL)
- **JDK Version:**  1.8.0_121

### Example Application

See https://github.com/rrsIPOV/dbm-env

**Comment by jameskleeh** [comment]
What are the steps to reproduce with the example project?

Did you try `grails datatool dbm-update` ?

**Comment by rrsIPOV** [comment]
>grails datatool dbm-update
| Error Command not found datatool

In the sample project, to reproduce, it should only be needed to run:
>grails -Dgrails.env=datatool dbm-update

The H2 database 'rdataDB' is a snapshot before the final change log, so it doesn't have the Author.email column which should be added.  This was the fastest way I could think of to show the issue that I'm seeing.  You will also notice in the stacktrace.log that the environment says 'development', while if you run  'grails -Dgrails.env=datatool run-app' it will run in the custom environment, and the environment will correctly be listed as 'datatool', although I don't really care what the logging output is if the execution works... 

I hope that's clearer.

**Comment by jameskleeh** [comment]
Here is a workaround: `./gradlew -Dgrails.env=datatool dbmUpdate`

**Comment by jameskleeh** [comment]
This was actually an issue with core. Fixed by https://github.com/grails/grails-core/commit/d780175f3680969596b429819857565c310b8e21
