### ISSUE TITLE
Installing plugin on Grails 3.2.9 downloads H2 dependencies on project using postgres

### ISSUE THREAD

**Issue by ppazos** [grails-plugins/grails-database-migration#136]
### Steps to Reproduce

1. Install following this guide http://guides.grails.org/grails-database-migration/guide/index.html
2. Dependencies

| Resolving Dependencies. Please wait...
Download https://repo.grails.org/grails/core/org/grails/plugins/database-migration/3.0.3/database-migration-3.0.3.pom
Download https://repo.grails.org/grails/core/org/liquibase/liquibase-core/3.5.3/liquibase-core-3.5.3.pom
Download https://repo.grails.org/grails/core/org/liquibase/liquibase-parent/3.5.3/liquibase-parent-3.5.3.pom
Download https://repo.grails.org/grails/core/org/liquibase/ext/liquibase-hibernate5/3.6/liquibase-hibernate5-3.6.pom
**Download https://repo.grails.org/grails/core/com/h2database/h2/1.4.192/h2-1.4.192.pom**
Download https://repo.grails.org/grails/core/org/grails/plugins/database-migration/3.0.3/database-migration-3.0.3.jar
Download https://repo.grails.org/grails/core/org/liquibase/liquibase-core/3.5.3/liquibase-core-3.5.3.jar
Download https://repo.grails.org/grails/core/org/liquibase/ext/liquibase-hibernate5/3.6/liquibase-hibernate5-3.6.jar
**Download https://repo.grails.org/grails/core/com/h2database/h2/1.4.192/h2-1.4.192.jar**

### Expected Behaviour

Use postgres, don't download H2 as dependency.

### Actual Behaviour

Downloads H2.

### Environment Information

- **Operating System**: MacOS 10.11.6
- **Grails Version:** 3.2.9
- **Plugin Version:** 3.0.3
- **Database:** Postgres
- **JDK Version:** 1.8.0_121

### Example Application

- https://github.com/ppazos/notes

**Comment by jameskleeh** [comment]
This has nothing to do with the database migration plugin. Run a dependency report with `./gradlew dependencies` to see where it is coming from

**Comment by ppazos** [comment]
@jameskleeh Will do, but this appeared right after adding the reference to this plugin.

**Comment by ppazos** [comment]
@jameskleeh it seems there is an H2 dependency from liquibase hibernate

+--- org.grails.plugins:database-migration:3.0.3
|    +--- org.liquibase:liquibase-core:3.5.3
|    |    \--- org.yaml:snakeyaml:1.17
|    \--- org.liquibase.ext:liquibase-hibernate5:3.6
|         \--- com.h2database:h2:1.4.192 -> 1.4.194
\--- org.liquibase:liquibase-core:3.5.3 (*)

**Comment by ppazos** [comment]
Please reopen this issue since the dependency is there.

**Comment by ppazos** [comment]
@jameskleeh did you checked the dependencies? should I report another issue with the same description?

**Comment by ppazos** [comment]
@jameskleeh should I report this again since I posted the dependencies of liquibase referencing h2 but got no feedback.
