### ISSUE TITLE
Error circular dependency on grails dbm-generate-gorm-changelog: hibernateDatastore <> userPasswordEncoderListener

### ISSUE THREAD

**Issue by ppazos** [grails-plugins/grails-database-migration#137]
### Steps to Reproduce

1. Follow this guide http://guides.grails.org/grails-database-migration/guide/index.html
2. $ grails dbm-generate-gorm-changelog changelog.groovy

Configuring Spring Security Core ...
... finished configuring Spring Security Core

2017-09-14 16:06:26.207 ERROR --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 
Context failed to load: Error creating bean with name 'authenticationUserDetailsService': Cannot resolve reference to bean 'userDetailsService' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userDetailsService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hibernateDatastore': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.grails.orm.hibernate.HibernateDatastore]: Constructor threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userPasswordEncoderListener': Cannot resolve reference to bean 'hibernateDatastore' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'hibernateDatastore': Requested bean is currently in creation: Is there an unresolvable circular reference?

***************************
APPLICATION FAILED TO START
***************************

Description:

The dependencies of some of the beans in the application context form a cycle:

   authenticationUserDetailsService
      ↓
   userDetailsService
┌─────┐
|  hibernateDatastore
↑     ↓
|  userPasswordEncoderListener
└─────┘

:dbmGenerateGormChangelog FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dbmGenerateGormChangelog'.

### Expected Behaviour

Generate the changelog

### Actual Behaviour

Error circular dependency

### Environment Information

- **Operating System**: MacOS 10.11.6
- **Grails Version:** 3.2.9
- **Plugin Version:** 3.0.3
- **Database:** Postgres
- **JDK Version:** 1.8.0_121

### Example Application

- https://github.com/ppazos/notes

**Comment by jameskleeh** [comment]
Dup of https://github.com/grails-plugins/grails-database-migration/issues/127

**Comment by ppazos** [comment]
@jameskleeh I'm now using elastic search as mentioned on #127. Not sure what is the issue or the solution.
