### ISSUE TITLE
Request: Support Liquibase 3.6.0+

### ISSUE THREAD

**Issue by matthew-long** [grails-plugins/grails-database-migration#146]
Liquibase 3.6.0 fixed an issue that stopped generation of diffs against SQL Server DB's with a case sensitive collation.

I'd like to take advantage of that fix with the database migration plugin.

I tried using liquibase 3.6.0 with this plugin but got an error as there's been some significant changes.

**Comment by puneetbehl** [comment]
This plugin depends on `liquibase-hibernate`. However, that need to published first to support Liquibase 3.6. 

Following is the issue describing the incompatibility: 
https://github.com/liquibase/liquibase-hibernate/issues/179

**Comment by niravassar** [comment]
This is now done due to checkin https://github.com/grails-plugins/grails-database-migration/commit/4320ebd18b0cebfbf605ef20649439e6121d9171
