### ISSUE TITLE
[Grails 4] Database Migration plugin issue

### ISSUE THREAD

**Issue by drennane** [grails-plugins/grails-database-migration#154]
Since upgrading to Grails 4, the migration scripts do not appear to be getting loaded from where they are configured. This results in the following error;

> liquibase.exception.ChangeLogParseException: java.lang.IllegalArgumentException: Script text to compile cannot be null!

Up to now, I had only specified the location on gradle config;

```
sourceSets {
    main {
        resources {
            srcDir 'grails-app/migrations'
        }
    }
}
```
I have since added the additional config provided by the plugin but to no avail;

`grails.plugin.databasemigration.changelogLocation = 'grails-app/migrations'`

Through debugging, I can see that the grails-app/migrations path does not appear to be added to the list of locations but also discovered that grails-app/conf is, so I temporarily dropped them all in there and voilà... the application fired up.

My understanding was that the default location was grails-app/migrations but would certainly expect that the configuration above is honoured.

- **Operating System**: Mac OSX High Sierra
- **Grails Version:** 4.0.0.M2
- **Plugin Version:** 3.0.4
- **Database:** MySql
- **JDK Version:** Java 11 (AdoptOpenJDK)

**Comment by joemccall86** [comment]
Appears in Grails 4.0.0.RC1 on Java 8 as well. It would appear that the `ClassLoaderResourceAccessor` is not picking up the additional directory on the classpath when it builds its `rootStrings` value.

**Comment by joemccall86** [comment]
This may be related: I have `@PropertySource` on my application that references a file in the classpath, and Grails 4/Spring Boot 2 fails to find that file after the upgrade. I think this is due to an underlying change in how Spring Boot 2 handles resources on the classpath.

**Comment by niravassar** [comment]
@drennane I have created sample project at https://github.com/niravassar/grails-dbmigration-four. We are working on changes to the plugin to release for Grails 4 RC2. I was able to run the changelog from the 'grails-app/migrations' directory.

Can you please upload a sample project? I will try and reproduce the issue there. 

Alternatively, you can look at the 4.0.0.BUILD-SNAPSHOT of this code and do a gradlew pTML, and use it in your app to see if the that version works. thanks.

**Comment by jameskleeh** [comment]
@joemccall86 @drennane The additional source set declaration in the build.gradle file must be above the dependencies section

**Comment by drennane** [comment]
Upgraded to latest in project above and moved the source set declaration as per @jameskleeh and I can confirm that it's all working now.
Much appreciated.

**Comment by beechovsky** [comment]
I am seeing this error still despite having both configuration items above, with the first correctly placed above dependencies as indicated in the documentation.

Operating System: macOS Big Sur 11.6.5
Grails Version: 4.0.10
Plugin Version: 3.1.0
Database: MySQL
JDK Version: 1.8.0_321
