### ISSUE TITLE
Support for afterColumn attribute in addColumn

### ISSUE THREAD

**Issue by robertoschwald** [grails-plugins/grails-database-migration#163]
Liquibase since 3.3.0 supports afterColumn to define the position of new columns.
It would be great if this can be reflected in the plugin gdsl as well

http://www.liquibase.org/documentation/column.html

Liquibase also supports "beforeColumn", but that is not supported by all databases. E.g. MySQL does not support beforeColumn, therefore I would omit it.

**Comment by bobbywarner** [comment]
Resolved with https://github.com/grails-plugins/grails-database-migration/pull/178
