### ISSUE TITLE
What happened to Grails 4 compatibility?

### ISSUE THREAD

**Issue by wuwu2000** [grails-plugins/grails-database-migration#174]
Bonjour!

I am curious, in your readme Grails 3 and 2 is listed as compatible. Since Grails 4 use Spring boot 2 and there is no org.springframework.boot.liquibase.CommonsLoggingLiquibaseLogger I am looking for a grails 4 compatible grails-database-migration.

I found some traces that something may have worked sometimes but I can't find absolutly no documentation about migrating to grails 4.

Could you please provide some text about the state of this project regarding to grails 4 for lost souls like me?

Thx a lot!

**Comment by niravassar** [comment]
It is compatible. Please see the guide with the example:
https://guides.grails.org/grails-database-migration/guide/index.html
