### ISSUE TITLE
Support Liquibase 4.0.0

### ISSUE THREAD

**Issue by mattlong-finocomp** [grails-plugins/grails-database-migration#177]
Liquibase 4.0.0 has been released

There's been some significant API changes which don't work with this plugin.

Could we get a new version of this plugin that supports Liquibase 4.x

**Comment by mattlong-finocomp** [comment]
@puneetbehl I've seen a bit of activity in this repo in the past few days. Is this issue on the roadmap?
I've been looking into upgrading an existing Grails application to 5.0.1 and noticed that the Micronaut BOM wants to bring in Liquibase 4.4.3 and Spring Boot is pinning it to 4.3.5 via its managed dependencies.
For now as a workaround I've set liquibase.version to 3.10.3 in gradle.properties but it would be great if that wasn't necessary.

**Comment by puneetbehl** [comment]
Yes, that is in the roadmap.
