### ISSUE TITLE
Grails 3 org.hibernate.HibernateException: No Session found for current thread

### ISSUE THREAD

**Issue by olliefreeman** [grails-plugins/grails-database-migration#38]
Don't know if this is a grails 3 issue or the plugin issue, or if I shouldn't be able to do this.

I want to preload data into the database for known datatypes, (reference data). 
This post is from 2010 so it is very possible capabilities have changed we shouldn't be able to do this
http://refactr.com/blog/2012/01/grails-database-migration-gotchas/
but I'd like to be able to call `save()` on a domain class from inside a change set however i'm getting a `no session found for current thread`. 

Is this intended behaviour or should i be able to do this?

**Comment by emilio2hd** [comment]
Same here :disappointed:

**Comment by emilio2hd** [comment]
@olliefreeman I guess GORM it's not supported anymore, the documentation says:
```groovy
change {
            // arbitrary code; make changes directly and/or return a
            // SqlStatement using the sqlStatement(SqlStatement sqlStatement)
            // method or multiple with sqlStatements(List sqlStatements)

            confirm 'change confirmation message'
         }
```
http://grails-plugins.github.io/grails-database-migration/docs/manual/guide/groovyChanges.html

**Comment by vitorbertazoli** [comment]
I'm having the same issue with Grails 3.2.0.M1 and database-migrations 2.0.0.RC4
here's a link to an example
https://github.com/vitorbertazoli/GrailsTest

**Comment by Schlogen** [comment]
The workaround is to wrap your code with `Domain.withNewSession { }`

**Comment by Schlogen** [comment]
Fixed in the current snapshot by https://github.com/grails-plugins/grails-database-migration/commit/d737ad60d9d40f50f0c1f9cfdcbe9e134e70c8ef
