### ISSUE TITLE
ignoredObjects doesn't appear to work

### ISSUE THREAD

**Issue by olliefreeman** [grails-plugins/grails-database-migration#39]
This may be just through a lack of documentation but my understanding of ignoredObjects is a list of strings of class objects to ignore for generating tables. 

Not sure if this is class.simpleName or class.canonicalName but either way its still producing changesets for the classes i want to ignore.

**Comment by bobbywarner** [comment]
@olliefreeman Not sure exactly when this changed, but it's actually called `grails.plugin.databasemigration.excludeObjects` now.  You can pass in a list of strings to `excludeObjects` just like you used to be able to for `ignoredObjects`.
