### ISSUE TITLE
WEB-INF/classes/migirations no longer in war on Grails 3

### ISSUE THREAD

**Issue by rvanderwerf** [grails-plugins/grails-database-migration#48]
I seem to have a regression from the grails 2 plugin. It used to be the migration scripts would be in WEB-INF/classes/migrations. Now they are all just dumped in the WEB-INF/classes dir which complicats things for me.

**Comment by Schlogen** [comment]
@rvanderwerf If you can supply some Gradle config to make this happen, I will try to include it in the plugin

**Comment by jameskleeh** [comment]
@rvanderwerf You can reopen if you're still interested in this
