### ISSUE TITLE
Issue with dataSource.passwordEncryptionCodec

### ISSUE THREAD

**Issue by tomcomer** [grails-plugins/grails-database-migration#50]
When using dataSource.passwordEncryptionCodec and running any dbm-* commands fails with a SQLException for failing to log into the database. I have verified that the application connects to the database just fine when doing 'grails run-app'. Also, if removing the dataSource.passwordEncryptionCodec and storing the database password in plain text, the dbm-* commands work just fine. So it is definitely an issue with the dataSource.passwordEncryptionCodec and what ever the plugin is doing to connect to the database. It is probably ignoring this property and using the encrypted password to try to connect.

**Comment by tomcomer** [comment]
Looks like this is related to: https://liquibase.jira.com/browse/CORE-1932
Forcing liquibase 3.3.2 by putting compile 'org.liquibase:liquibase-core:3.3.2' in the build.gradle file does not fix the issue.

**Comment by tomcomer** [comment]
Trying with the latest version of Liquibase 3.4.2 also does not solve the issue.

The actual exception when trying to connect to my local MySQL database is:

Command execution error: java.sql.SQLException: Access denied for user '<my user>'@'localhost' (using password: YES)

Commenting out dataSource.passwordEncryptionCodec and changing the password to be the unencrypted version fixes this, so it is definitely caused by dataSource.passwordEncryptionCodec.

**Comment by Schlogen** [comment]
@tomcomer What version of Grails / dbm?

**Comment by Schlogen** [comment]
Nevermind, looks like this was resolved here: https://github.com/grails-plugins/grails-database-migration/pull/52/files
