### ISSUE TITLE
Can not specify environment for dbm-generate-gorm-changelog

### ISSUE THREAD

**Issue by snimavat** [grails-plugins/grails-database-migration#54]
When i run ```> grails development dbm-generate-gorm-changelog base.groovy ```

It gives error 

```
| Error Command not found development
Did you mean: open or dependency-report or dbm-generate-changelog?

```

**Comment by ayaskevich** [comment]
Try:
grails dev dbm-generate-gorm-changelog base.groovy

**Comment by Schlogen** [comment]
@snimavat `grails dev ...` is the syntax
