### ISSUE TITLE
No such property sql within a grailsCondition

### ISSUE THREAD

**Issue by HopefulLlama** [grails-plugins/grails-database-migration#55]
Having something that looks like:

    databaseChangeLog = {

        changeSet(author: "Rick Astley", id: "Not a stranger to love") {

            preConditions {

                grailsCondition {

                    check {

                        sql.<literally anything>
    ...

will fail as it returns the exception 
`portal-changelog.groovy : No such property: sql for class: never-gonna-give-you-up.Script1`

**Comment by Schlogen** [comment]
It is `grailsPrecondition`, not `grailsCondition`

**Comment by HopefulLlama** [comment]
Experiencing this problem, even with the correction of `grailsPrecondition`.

**Comment by jameskleeh** [comment]
@HopefulLlama Then open a new issue with an example project
