### ISSUE TITLE
The plugin is not generating the diff as expected.

### ISSUE THREAD

**Issue by ShurikAg** [grails-plugins/grails-database-migration#60]
I have an existing app in which I used to use previous version of this plugin.
I needed to upgrade together with grails upgrade and I started to have bunch of problems, so I decided to start migration history from scratch. However, before I started dealing with it, I already made some changes to existing domain classes and added one new. 
My plan was to generate a changelog based on my current prod DB and then generate a diff for the changes I made. Sounds simple and straightforward; however, it didn't work out as expected. Here is what I did:

1. Dumped prod DB
2. Removed liquibase tables
3. Run: `grails dbm-generate-changelog changelog-init.xml --add` 
At this point, I expected changelog-init.xml to contain the current state of DB. But, instead it applied the changes based on my models first, and then tried generating the diff. Eventually I ended up with a changelog including my entire existing DB with changes applied from gorm.

What am I doing wrong here?

**Comment by Schlogen** [comment]
@ShurikAg Most likely your `dbCreate` setting was set to `update`, either directly or by not setting the setting at all. If you find that is not the cause, feel free to reopen with an example project.
