### ISSUE TITLE
Mapping `tablePerHierarchy` causes a NPE when executing `dbm-gorm-diff`

### ISSUE THREAD

**Issue by bassmartin** [grails-plugins/grails-database-migration#68]
Project to reproduce : https://github.com/bassmartin/grails-database-migration-tablePerHierarchy-issue

Checkout the project and execute a `dbm-gorm-diff` it will fail with a NPE.

The project has one Parent domain class and one Child domain class only.

**Comment by Schlogen** [comment]
Once https://github.com/grails/grails-data-mapping/pull/737 is merged and a new version of the hibernate4 gorm is released, that can be included in the next release of this plugin which will resolve this issue.

**Comment by Schlogen** [comment]
@bassmartin Can you verify `hibernate4:5.0.9.BUILD-SNAPSHOT` resolves this problem for you?

**Comment by bassmartin** [comment]
I'll check next week. Today is Holiday here ;-)

--
Sébastien Martin

**Comment by Schlogen** [comment]
Fixed by https://github.com/grails/grails-data-mapping/commit/57cece76bcb065d1340e36328f0baa21dd5289d9
