### ISSUE TITLE
Possible to switch liquibase version?

### ISSUE THREAD

**Issue by immutability** [grails-plugins/grails-database-migration#72]
Hello! I'm just starting with the dbm plugin and ran into an issue with PostgreSQL timestamp columns. It looks like the plugin version 1.4.1 is using Liquibase 2.0.5 and the issue (see liquibase jira CORE-877 and CORE-1906) was supposedly fixed in Liquibase 3.2.0. Is it possible to somehow (easily) switch to a newer liquibase version with dbm 1.4.1? Or only with dbm 2.0.0 (if that's the case, will 2.0.0 support Grails 2.5.x or only Grails 3)? Thanks for any guidance in advance!

**Comment by Schlogen** [comment]
@immutability There aren't any plans to update the Grails 2 version of this plugin. dbm 2.x (Grails 3 only) can be updated to support the latest version of liquibase.

**Comment by immutability** [comment]
Thanks, that makes sense. We just didn't have time/resources to migrate to Grails 3 yet. For now I added a sql changeset to alter the timestamps on PSQL as a workaround.

**Comment by jameskleeh** [comment]
The 2.x and 3.x lines have been updated to the latest version of liquibase. Closing this as there are no plans to update 1.x
