### ISSUE TITLE
Tests to verify this plugin works correctly when updating dependencies.

### ISSUE THREAD

**Issue by jesperronn** [grails-plugins/grails-database-migration#73]
I have worked on a handful of projects using this plugin. I would like this plugin to have tests, that can verify behaviour, especially when dependencies should be updated. 

Some grails developers tend to be reluctant to update dependencies, probably because they burnt their fingers previously. 

By having tests, it will be easy to spot which dependencies will break. 

And having continuous integration set up to build will be awesome. Grails has a Travis build. This plugin could have that too.

Who wants to help writing tests for this plugin?

**Comment by Schlogen** [comment]
@jesperronn This plugin does have tests. Can you be more specific about what you're asking?

**Comment by jesperronn** [comment]
@Schlogen thanks! I now realize that there is a Travis CI build already set up. And I also see that the build is running some tests. (5 integration tests, as far as I could see) 

What I meant was to set up testing of this plugin with different Grails versions and Java versions. Travis supports this, and I think it could benefit users to know that their specific Grails version is supported.
