### ISSUE TITLE
Use new feature of 3.1.x to allow skipping of Bootstrap execution

### ISSUE THREAD

**Issue by Schlogen** [grails-plugins/grails-database-migration#79]
https://github.com/grails/grails-core/pull/10042

**Comment by Schlogen** [comment]
Fixed in the current snapshot by https://github.com/grails-plugins/grails-database-migration/commit/d737ad60d9d40f50f0c1f9cfdcbe9e134e70c8ef

**Comment by snimavat** [comment]
@Schlogen is this available now ?

**Comment by snimavat** [comment]
Perfect @Schlogen tried with 2.0.0.BUILD-SNAPSHOT - and it works..
