### ISSUE TITLE
dbm-generate-gorm-changelog does not automatically create indexs

### ISSUE THREAD

**Issue by snimavat** [grails-plugins/grails-database-migration#82]
So if i have specified indexes in my gorm mappings as explained [here](http://docs.grails.org/latest/guide/GORM.html#databaseIndices) 

And generate dbm-generate-gorm-changelog - it does not automatically create indexes.

**Comment by robertoschwald** [comment]
duplicate of #74 ?

**Comment by jameskleeh** [comment]
Duplicate
