### ISSUE TITLE
Can't ignore/exclude domain classs

### ISSUE THREAD

**Issue by thomasoreilly** [grails-plugins/grails-database-migration#83]
Hi,
Seems to be a problem when trying to use "grails.plugin.databasemigration.ignoredObjects" property to ignore some domain classes.  Nothing happens, as in domain classes aren't being ignored. 

I also tried to use "grails.plugin.databasemigration.excludeObjects" as the source code seems to be looking out for this property. I get the following when using the above. 
Command execution error: liquibase.command.CommandExecutionException: java.lang.NullPointerException

This happens with the grails dbm-gorm-diff command.

grails version=3.1.8
grails-database-migration version=2.0.0.RC4
java  version=1.8.0_91 (64-bit)
hibernate4 version=5.0.10

**Comment by mjcmatrix** [comment]
Me too.

**Comment by robertoschwald** [comment]
This one worked for me:

```
grails {
  plugin {
    databasemigration {
      updateOnStartFileNames = ['changelog.groovy']
      updateOnStart = true
      dropOnStart = false
      // Quartz tables. Note: This field is currently UNDOCUMENTED for Grails 3.
      excludeObjects = ['QRTZ_BLOB_TRIGGERS', 'QRTZ_CALENDARS', 'QRTZ_CRON_TRIGGERS', 'QRTZ_FIRED_TRIGGERS', 'QRTZ_JOB_DETAILS', 'QRTZ_LOCKS', 'QRTZ_PAUSED_TRIGGER_GRPS', 'QRTZ_SCHEDULER_STATE', 'QRTZ_SIMPLE_TRIGGERS', 'QRTZ_SIMPROP_TRIGGERS', 'QRTZ_TRIGGERS']
    }
  }
}
```

**Comment by jameskleeh** [comment]
@thomasoreilly Can you include an example project?

**Comment by jameskleeh** [comment]
Added to docs `includeObjects` and `excludeObjects`
