### ISSUE TITLE
documentation for version 2

### ISSUE THREAD

**Issue by meltzow** [grails-plugins/grails-database-migration#84]
this is only für version 1 : http://grails-plugins.github.io/grails-database-migration/1.4.0/

**Comment by robertoschwald** [comment]
This  http://grails-plugins.github.io/grails-database-migration/2.0.0.RC4/ is for 2.0.0, but is still not valid for some configurations. Will create issues for it.

**Comment by meltzow** [comment]
looks good. thx. So I will close the issue
