### ISSUE TITLE
grails3 plugin with domain classes - crash

### ISSUE THREAD

**Issue by meltzow** [grails-plugins/grails-database-migration#85]
hi,

we have a grails3 app with local plugins (domain classes included). Is there any working example for it? 
for example dbm-gorm-diff isn't working. Grails want to call dbm-gorm-diff inside the plugin directory. There it crashes with: java.lang.ClassNotFoundException: org.hibernate.cfg.Configuration
if we insert hibernate as dependency, we got : 
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'persistenceInterceptor': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire method: public void org.grails.orm.hibernate4.support.AggregatePersistenceContextInterceptor.setHibernateDatastores(org.grails.orm.hibernate.AbstractHibernateDatastore[]); nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.grails.orm.hibernate.AbstractHibernateDatastore] found for dependency [array of org.grails.orm.hibernate.AbstractHibernateDatastore]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}

how can we solve it?
thx.

**Comment by jameskleeh** [comment]
@meltzow Can you please confirm this is still occuring with version `2.0.0.BUILD-SNAPSHOT` of the plugin, and if so, attach an example project?

**Comment by jameskleeh** [comment]
Closing this due to lack of response. Create a new issue with an example project if you are still facing this issue with version 2.0.0.
