### ISSUE TITLE
Documentation errors for 2.0.0.x

### ISSUE THREAD

**Issue by robertoschwald** [grails-plugins/grails-database-migration#87]
1. changelogFileName > grails.plugin.databasemigration.updateOnStartFileName 

http://grails-plugins.github.io/grails-database-migration/2.0.0.RC4/guide/configuration.html

states wrongly on several places:
```
grails.plugin.databasemigration.changelogFileName
```

Correct:
```
grails.plugin.databasemigration.updateOnStartFileName
```
"changelogFileName" is gone.

2. updateOnStartFileNames:
This seems to be gone. Only updateOnStartFileName is there.

**Comment by jameskleeh** [comment]
@robertoschwald `changelogFileName` is used for example to determine which file to run when executing `dbmUpdate`.

**Comment by jameskleeh** [comment]
What is incorrect is `updateOnStartFileNames`. It should only be `updateOnStartFileName`

**Comment by jameskleeh** [comment]
Fixed by https://github.com/grails-plugins/grails-database-migration/commit/728a98a67d2611cade1d01657d7577ef699616c3
