### ISSUE TITLE
changelog.xml does not exist when lib is shared in Tomcat

### ISSUE THREAD

**Issue by brunohoff** [grails-plugins/grails-database-migration#89]
When the application is deployed with the dependencies JAR files in the /lib folder in Tomcat 7 it can't find the changelog.xml file.

**Comment by jameskleeh** [comment]
@brunohoff Can you provide me some steps to reproduce and an example project?

**Comment by jameskleeh** [comment]
Closing this due to lack of response. Create a new issue with with steps to reproduce and an example project if you are still facing this issue with version 2.0.0(hibernate4) or 3.0.0(hibernate5)
