### ISSUE TITLE
Migrate documentation to Grails 3 for 2.0.0

### ISSUE THREAD

**Issue by robertoschwald** [grails-plugins/grails-database-migration#91]
PR follows

**Comment by jameskleeh** [comment]
Be sure to do it against the 2.x branch. I can merge it up to master.

**Comment by burtbeckwith** [comment]
It would be good to include removing the section on Autobase and the discussion about the Searchable plugin from gettingStarted.adoc with this since both are quite dated and not applicable in 3.x
