### ISSUE TITLE
SchemaComparison failure in Liquibase

### ISSUE THREAD

**Issue by tlefevre** [grails-plugins/grails-database-migration#96]
When using version 2.0.0 of the plugin and running it, I get the following: 

Command execution error: liquibase.diff.output.DiffOutputControl.<init>(ZZZ[Lliquibase/diff/compare/CompareControl$SchemaComparison;)V

When using version 2.0.0.RC4 of the plugin, it works. 

I can see that there has been changes made in the Liquibase dependencies. I am having little luck coaxing any relevant info out of gradle.

**Comment by jameskleeh** [comment]
You're using an old version of liquibase: http://grails-plugins.github.io/grails-database-migration/2.0.x/index.html#gettingStarted

compile 'org.liquibase:liquibase-core:3.5.3'
