### ISSUE TITLE
| Error Command not found dbm-generate-changelog 

### ISSUE THREAD

**Issue by alibazlamit** [grails-plugins/grails-database-migration#99]
Trying to run this command `grails dbm-generate-changelog changelog.groovy` and i got this error.
Running grails 3.2.0 on windows.

Any ideas?

`| Error Command not found dbm-generate-changelog
Did you mean: dbm-create-changelog or dbm-changelog-to-groovy or generate-all?`

**Comment by jameskleeh** [comment]
Are you attempting to generate a changelog from your database?

**Comment by alibazlamit** [comment]
using this version `org.grails.plugins:database-migration:3.0.0` i tried both from the db and from the domain class using this command `grails dbm-generate-gorm-changelog changelog.groovy` and i got the same result.

Thanks

**Comment by Kipriz** [comment]
I have a similar issue. I'm using Grails 3.2.3 and the plugin 3.0.0
Any plugin's command fails to execute. I tried to add for a quite big existing project. For completely new and almost empty project, the plugin works fine.

**Comment by jameskleeh** [comment]
@Kipriz @alibazlamit Do you have the plugin defined like so in your build.gradle?

```
buildscript {
   dependencies {
      ...
      classpath 'org.grails.plugins:database-migration:3.0.0'
   }
}

dependencies {
   ...
     compile 'org.grails.plugins:database-migration:3.0.0'
}
```

**Comment by alibazlamit** [comment]
Yes i have those configured in the build.gradle

```buildscript {
   ....
    dependencies {
        classpath 'org.grails.plugins:database-migration:3.0.0'
    }
}```
```dependencies {
    compile 'org.grails.plugins:database-migration:3.0.0'
}```

**Comment by Kipriz** [comment]
@jameskleeh , I also have all necessary settings.
Can you try to run dbm-status on your env for this project: https://github.com/Kipriz/gr323 ?
It is created by Grails 3.2.3, then I added Client entity and I'm trying to run at least dbm-status. It does not work.

**Comment by alibazlamit** [comment]
@jameskleeh do you think that could be a solution for this problem soon, or should i start looking for alternatives?
Thanks

**Comment by jameskleeh** [comment]
@Kipriz Here you go:

```
Jamess-MacBook-Pro:IdeaProjects jameskleeh$ git clone https://github.com/Kipriz/gr323
Cloning into 'gr323'...
remote: Counting objects: 90, done.
remote: Compressing objects: 100% (69/69), done.
remote: Total 90 (delta 6), reused 90 (delta 6), pack-reused 0
Unpacking objects: 100% (90/90), done.
Checking connectivity... done.
Jamess-MacBook-Pro:IdeaProjects jameskleeh$ cd gr323
Jamess-MacBook-Pro:gr323 jameskleeh$ ./grailsw dbmStatus
-bash: ./grailsw: Permission denied
Jamess-MacBook-Pro:gr323 jameskleeh$ chmod u+x grailsw*
| Resolving Dependencies. Please wait...
Download https://repo.grails.org/grails/core/org/grails/plugins/database-migration/3.0.0/database-migration-3.0.0.pom
Download https://repo.grails.org/grails/core/org/grails/plugins/database-migration/3.0.0/database-migration-3.0.0.jar

CONFIGURE SUCCESSFUL

Total time: 19.755 secs
:compileJava UP-TO-DATE
:compileGroovy
:buildProperties
:processResources
:classes
:findMainClass
:dbmStatus
objc[30807]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/bin/java (0x10b4ad4c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x10b5754e0). One of the two will be used. Which one is undefined.
Command execution error: grails-app/migrations must be a directory
:dbmStatus FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dbmStatus'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 50.839 secs
| Error Command [dbmStatus] error: Could not execute build using Gradle installation '/Users/jameskleeh/.sdkman/candidates/gradle/current'. (Use --stacktrace to see the full trace)
```

**Comment by jameskleeh** [comment]
@alibazlamit I'm not convinced there is a problem to be solved.  If you can produce a sample application, I'll be glad to look at it.

**Comment by alibazlamit** [comment]
@jameskleeh apologies it seems that i was referencing an older version of the migration from before, i inspected the whole gradle.build file and it was there somewhere in between, the problem is gone.
